[general]
import = [
  "tokyonight.toml"
]

[window]
decorations = "None"
opacity = 0.8

[window.padding]
x = 10
y = 10

[font]
size = 16

[font.normal]
family = "hasklug nerd font mono"
style = "regular"

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true
