# Shell
shell /usr/bin/zsh

# Mod Key
kitty_mod ctrl+shift

# THEME
# Tokyo Night
include tokyo-night.conf
# END_THEME

# Fonts
font_family Hasklug Nerd Font
bold_font	Hasklug Nerd Font Bold
italic_font	Hasklug Nerd Font Italic
bold_italic_font	Hasklug Nerd Font Bold Italic

font_size 16

# Transparency
background_opacity 0.8

# Windows
window_margin_width 10
single_window_margin_width 5

# Tab Look
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol *

# MAPPED KEYS
map F1 new_window_with_cwd
map F2 launch --cwd=current /usr/bin/nvim .
